# Labeler configuration for actions/labeler@v5
# https://github.com/actions/labeler

firmware:
  - changed-files:
    - any-glob-to-any-file:
      - edge/**

component:
  - changed-files:
    - any-glob-to-any-file:
      - edge/components/**

camera:
  - changed-files:
    - any-glob-to-any-file:
      - edge/components/camera_capture/**

image-processing:
  - changed-files:
    - any-glob-to-any-file:
      - edge/components/downscaler/**

optical-flow:
  - changed-files:
    - any-glob-to-any-file:
      - edge/components/optical_flow/**

application:
  - changed-files:
    - any-glob-to-any-file:
      - edge/main/**

tests:
  - changed-files:
    - any-glob-to-any-file:
      - edge/test/**

ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - "*.md"

legal:
  - changed-files:
    - any-glob-to-any-file:
      - LICENSE

changelog:
  - changed-files:
    - any-glob-to-any-file:
      - CHANGELOG.md
