name: ClusterFuzzLite PR Fuzzing

on:
  pull_request:
    paths:
      - 'edge/**'
      - '.clusterfuzzlite/**'

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945ed7cd6ae5137b # v1
        with:
          language: c++
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945ed7cd6ae5137b # v1
        with:
          fuzz-seconds: 60
          mode: 'code-change'
          sanitizer: 'address'
